questionnaires for consultations
EscolaLMS/Front pull request #506
Opened 2024-11-07 16:31 UTC by victazzz

2024-11-12 14:32 UTC, mcholcha requested changes

2024-11-12 14:32 UTC, mcholcha commented on src/components/Consultations/ConsultationCard/JitsyMeeting/Message/index.tsx
> +        Zgoda na analizę emocji i uwagi
translation

2024-11-12 14:32 UTC, mcholcha commented on src/components/Consultations/ConsultationCard/JitsyMeeting/index.tsx
> +        console.log("Show modal");
log

2024-11-12 14:32 UTC, mcholcha commented on src/components/Consultations/ConsultationTutorCard/Content/DateInfo/index.tsx
> +  console.log("ConsultationTutorCardContentDateInfo", consultation);
log

2024-11-12 14:32 UTC, mcholcha commented on src/components/Courses/Course/CoursePanelLayout/FinishPage/Rate/index.tsx
> +    // error,
comment

2024-11-12 14:32 UTC, KrystianEscolaSoft commented on src/components/Consultations/ConsultationCard/JitsyMeeting/index.tsx
> +        console.log("Show modal");
console.log

2024-11-12 14:34 UTC, KrystianEscolaSoft commented on src/components/Consultations/ConsultationTutorCard/Content/DateInfo/index.tsx
> +  console.log("ConsultationTutorCardContentDateInfo", consultation);
.

2024-11-14 09:16 UTC, mcholcha approved these changes

2024-11-14 09:17 UTC, merged